"""empty message

Revision ID: d0de63f6deef
Revises: 83cbc2db4e82
Create Date: 2022-05-11 11:57:44.582861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0de63f6deef'
down_revision = '83cbc2db4e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nueva_direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buscar', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nueva_direccion')
    # ### end Alembic commands ###
